### ISSUE TITLE
travis-ci.org migrated to travis-ci.com

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [YangModels/yang#1000]
travis-ci-.org is not automatically starting the job anymore hence the webhook from .travis file
```
notifications:
  webhooks:
    urls:
      - https://yangcatalog.org/api/checkComplete
      - https://yang.amsl.com/api/checkComplete
 ```

to merge PR from IETF draft yang file will never be trigered and merged which means they will just stack in PRs. travis-ci.org is migrated to travis-ci.com and first time setup needs to be done.

the message in travis-ci.org is stating the following:

`Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.`

Please take action to fix this.
